In [27]:
!pip install kafka-python

Requirement already satisfied: kafka-python in .\appdata\local\programs\python\python39\lib\site-packages (2.3.0)

In [28]:
import pandas as pd
from kafka import KafkaProducer, KafkaConsumer
from time import sleep
from json import dumps
import json

In [29]:
producer = KafkaProducer(bootstrap_servers=['localhost:9092'],
                         value_serializer = lambda x:
                         dumps(x).encode('utf-8'))

In [30]:
producer.send('project2', value= {'name':'Deeksha'})

In [31]:
import pandas as pd

In [32]:
df = pd.read_csv("zomato.csv")

In [33]:
df.drop("url" ,  axis=1)

,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
0,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari
1,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari
2,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari
3,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari
4,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51712,"Four Points by Sheraton Bengaluru, 43/3, White...",Best Brews - Four Points by Sheraton Bengaluru...,No,No,3.6 /5,27,080 40301477,Whitefield,Bar,NaN,Continental,"1,500","[('Rated 5.0', ""RATED\n Food and service are ...",[],Pubs and bars,Whitefield
51713,"Number 10, Garudachar Palya, Mahadevapura, Whi...",Vinod Bar And Restaurant,No,No,NaN,0,+91 8197675843,Whitefield,Bar,NaN,Finger Food,600,[],[],Pubs and bars,Whitefield
51714,Sheraton Grand Bengaluru Whitefield Hotel & Co...,Plunge - Sheraton Grand Bengaluru Whitefield H...,No,No,NaN,0,NaN,Whitefield,Bar,NaN,Finger Food,"2,000",[],[],Pubs and bars,Whitefield
51715,Sheraton Grand Bengaluru Whitefield Hotel & Co...,Chime - Sheraton Grand Bengaluru Whitefield Ho...,No,Yes,4.3 /5,236,080 49652769,"ITPL Main Road, Whitefield",Bar,"Cocktails, Pizza, Buttermilk",Finger Food,"2,500","[('Rated 4.0', 'RATED\n Nice and friendly pla...",[],Pubs and bars,Whitefield
51716,"ITPL Main Road, KIADB Export Promotion Industr...",The Nest - The Den Bengaluru,No,No,3.4 /5,13,+91 8071117272,"ITPL Main Road, Whitefield","Bar, Casual Dining",NaN,"Finger Food, North Indian, Continental","1,500","[('Rated 5.0', 'RATED\n Great ambience , look...",[],Pubs and bars,Whitefield

In [34]:
df = df.sample(n=5000, random_state=42)

In [35]:
df

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
8440,https://www.zomato.com/bangalore/kalingas-btm?...,"399, 16th Main, N.S Palya, BTM, Bangalore",Kalingas,Yes,No,3.9/5,179,080 42038180,BTM,Quick Bites,"Rasgulla, Mutton Kosha, Chicken Kasha, Samosa ...","Oriya, Fast Food",250,"[('Rated 3.0', 'RATED\n A pocket friendly foo...",[],Delivery,BTM
23575,https://www.zomato.com/bangalore/angel-restaur...,"1st Cross, Bilekahalli, Near IIMB College, Ban...",Angel Restaurant,Yes,No,2.8/5,165,+91 9035699847\r\n+91 9880714970,Bannerghatta Road,Quick Bites,NaN,"Kerala, South Indian, North Indian",450,"[('Rated 1.0', 'RATED\n I cannot say a word a...","['Kappa', 'Kappa Biryani', 'Chicken Biryani', ...",Dine-out,JP Nagar
16711,https://www.zomato.com/bangalore/cafe-talkhous...,"4rd floor, 7th Cross, Opposite to BMTC Bus Dep...",Cafe Talkhouse,No,No,3.8/5,23,NaN,HSR,Quick Bites,NaN,North Indian,NaN,"[('Rated 5.0', 'RATED\n Have been to this pla...",[],Delivery,HSR
42588,https://www.zomato.com/bangalore/paratha-xpres...,"17/1 Cambridge Road, Opposite The Frank Antony...",Paratha Xpress,No,No,3.5 /5,8,065535 07908402366,Ulsoor,Quick Bites,NaN,"North Indian, Chinese",200,"[('Rated 5.0', 'RATED\n good job!'), ('Rated ...",[],Delivery,MG Road
5266,https://www.zomato.com/bangalore/classic-lassi...,"Skywalk, 5/1, Near Body Craft, Assaye Road, Ul...",Classic Lassi Shop,Yes,No,3.5/5,43,+91 8792958786\r\r\n+91 8073579529,Ulsoor,Beverage Shop,NaN,"Beverages, Ice Cream",150,"[('Rated 3.0', 'RATED\n I have mixed feeling ...","['Fruit Salad with Ice Cream', 'Brownie with I...",Delivery,Brigade Road
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2174,https://www.zomato.com/bangalore/le-centre-jeu...,"61, G P Rajarathnam Road, BTS Layout, Arekere,...",Le Centre Jeunesse,Yes,No,NaN,0,+91 9035599429,Bannerghatta Road,Quick Bites,NaN,Continental,400,[],[],Dine-out,Bannerghatta Road
44384,https://www.zomato.com/bangalore/the-waffle-ya...,"80 Feet Road, RMV Extension, Ashwathnagar, New...",The Waffle Yard,No,No,4.2 /5,149,+91 9886540545\n+91 7977178067,New BEL Road,"Dessert Parlor, Quick Bites","Nutella Waffle, Chocolate Waffles, Banana Caramel","Desserts, Fast Food",300,"[('Rated 4.0', 'RATED\n Was craving for waffl...",[],Desserts,New BEL Road
45717,https://www.zomato.com/bangalore/jaishree-pavi...,"175, GNS Arcade, Near Thippasandra Main Road, ...",Jaishree Pavilion,No,No,3.7 /5,36,080 41463848,Thippasandra,Casual Dining,NaN,"North Indian, South Indian, Chinese",700,"[('Rated 5.0', 'RATED\n A place with good amb...",[],Dine-out,Old Airport Road
33839,https://www.zomato.com/bangalore/imperial-rest...,"47, 6th Cross, 6th Block, Koramangala 6th Bloc...",Imperial Restaurant,Yes,No,3.6 /5,242,+91 8792003031\n080 65603031,Koramangala 6th Block,Casual Dining,"Chicken Grill, Shawarma, Ghee Rice, Chicken Bu...","Seafood, Biryani, South Indian, Chettinad, Chi...",800,"[('Rated 4.0', 'RATED\n One of the favourite ...",[],Dine-out,Koramangala 6th Block
39663,https://www.zomato.com/bangalore/dominos-pizza...,"22, 5th Cross, Near Malleshwaram Circle, Malle...",Domino's Pizza,Yes,No,4.0 /5,377,080 23343330\n18602100000,Malleshwaram,Quick Bites,"Pizza, Garlic Bread, Chocolava Cake","Pizza, Fast Food",400,"[('Rated 4.0', 'RATED\n So I visited the outl...","['Margherita', 'Farmhouse', 'Mexican Green Wav...",Delivery,Malleshwaram

In [36]:
df.sample(1).to_dict(orient = "records")[0]

{'url': 'https://www.zomato.com/bangalore/grab-n-dash-new-bel-road-bangalore?context=eyJzZSI6eyJlIjpbIjE4NDMwMzc0IiwiMTg2NDE3NTQiLCIxODY0MTc1MCIsIjE4NjU3MjkxIiwxODY5Nzg0NSwiMTg3MjU1MDEiLCIxODY1ODIwNSIsIjE4NjU5MzAzIiwiMTg3NTQ3OTMiLCIxODgwNjAwMiIsIjE4OTA1MjAwIiwiMTg5MTU3NTkiLCIxODY4MzY5MyIsIjE4NjM4NTExIiwiMTgzMzMxNjAiLCIxODg1NjkyNyIsIjE4ODIwNjI2IiwiMTg3NjM5NDgiLCIxODQ4NzE3MSIsIjE4NTcyNTE1IiwiMTgyNzAxODUiXSwidCI6IkRpbmUtT3V0IFJlc3RhdXJhbnRzIGluIE5ldyBCRUwgUm9hZCJ9fQ==',
 'address': 'F790, Bharath Nagar, East West College road, Opp to East West College, New BEL Road, Bangalore',
 'name': "Grab 'n' Dash",
 'online_order': 'No',
 'book_table': 'No',
 'rate': nan,
 'votes': 0,
 'phone': '+91 9148489898',
 'location': 'New BEL Road',
 'rest_type': 'Quick Bites',
 'dish_liked': nan,
 'cuisines': 'Fast Food',
 'approx_cost(for two people)': '200',
 'reviews_list': "[('Rated 5.0', 'RATED\\n  Ambiance is great, Food is great. Fairly new space but everything looks promising. Almost the best place in the area for quick bite or a big burger meal!')]",
 'menu_item': '[]',
 'listed_in(type)': 'Dine-out',
 'listed_in(city)': 'New BEL Road'}

In [39]:

import time
while True:
    data = df.sample(1).to_dict(orient="records")[0]
    producer.send('project2', value=data)
    producer.flush()   # 👈 IMPORTANT
    print("Sent:", data)
    time.sleep(1)

Sent: {'url': 'https://www.zomato.com/bangalore/tipsy-bull-the-bar-exchange-bellandur?context=eyJzZSI6eyJlIjpbIjE4NDY3MjUzIiwiMTg1Mzg2MjEiLCIxODI2MzQwNiIsIjUzNzgyIiwxODI4MDU5NiwiMTg5MzMzMzMiLCIxODY1NDExOCIsIjE4Mzg2MDY0IiwiNTY5NTMiLCIxODY3NDUyNCIsIjE4NDIyODk4IiwiMTg0MjI5MjIiLCIxODQyNDA1NSIsIjE4NTMxMDY3IiwiMTg0NzA3ODEiLCI1MDg2NCIsIjE4MzQ2MzY3IiwiMTg1MTQwMTQiXSwidCI6IkRlbGl2ZXJ5IFJlc3RhdXJhbnRzIGluIFNhcmphcHVyIFJvYWQifX0=', 'address': '24-26, 414/80/2, Varthur Hobli, Outer Ring Road', 'name': 'Tipsy Bull - The Bar Exchange', 'online_order': 'Yes', 'book_table': 'Yes', 'rate': '4.4 /5', 'votes': 2232, 'phone': '080 49653133', 'location': 'Bellandur', 'rest_type': 'Bar, Casual Dining', 'dish_liked': 'Falafel, Cocktails, Mocktails, Sea Food, Spring Roll, Mutton Pepper Fry, Pasta', 'cuisines': 'North Indian, Chinese, Continental, Mexican', 'approx_cost(for two people)': '1,400', 'reviews_list': '[(\'Rated 4.0\', "RATED\\n  Definitely one of the best place to hang out near Marathalli/Belandur area. From out side it\'s hard to realize but once you in, will find a huge area with a four side bar counter at the center. This place is partially covered and have a loft area perfect for private party or a large group.\\n\\nIf you don\'t know it\'s a Bar Exchange (recent time very famous in Bangalore) where you can order your fav drinks thru a mobile app with a option of burgaining, kinda auction.\\n\\nIt\'s their 2md outlet in Bangalore, first one located at Indiranagar. Foods menu is quite large with lots of options and they are mostly good. Must try their Pizza and Nachos, I liked them a lot Chicken kabab also very soft and yummy. In drinks try LIT and MaiTai.\\n\\nOver all it\'s a nice place.specially during sport events."), (\'Rated 4.0\', \'RATED\\n  Whatta awesome pub! Good crowd even for a weekday. Located right next to the main road. The concept of bar exchange is very Innovative and attractive. Would love to come here more often.\'), (\'Rated 5.0\', \'RATED\\n  Amazing place and I really like the concept\\nOne of my favourite place in Bangalore\\n\\nI totally love this place\\nThe interior are too good\\nAlso the dj set looks amazing\\n\\nReally worth the price\\nTotally value for money\\nThe service too is just amazing\\nFood tooo\\n\\nBeen here quiet a few time,I have totally enjoyed it\'), (\'Rated 4.0\', "RATED\\n  Really good place to happy with friends at any time of the day!!!\\nLoved the food, drinks, service and everything\\nBeing a bar exchange, it\'s rates are much lower and it\'s the only one in the area\\nWould recommend a visit"), (\'Rated 4.0\', \'RATED\\n  Tipsy Bull was a great way to unwind on a Friday evening after the end of a stressful week. The ambience is ok, the space is great though, the service and the food were impeccable. The draughts were priced decently and it was great trying them out. The music was ok and dancing soon commenced. All in all, lively and welcoming.\'), (\'Rated 4.0\', \'RATED\\n  Was here on a weekday evening for a quick drink and quite liked the rooftop ambiance and bar x change concept. Settled for a table overseeing the out ring road traffic.\\nFood is decent with a wide choice of beverages and off course depends on the rates one switch between beers and some hard liquor or classic cocktails.\\nIdeal for office parties or a catch up with friends.\'), (\'Rated 5.0\', \'RATED\\n  My friend and I visited this roof top bar exchange. We ordered beer pitchers and some starters both were good. Service also was really good and friendly staffs.\'), (\'Rated 4.0\', \'RATED\\n  Great place to hangout with friends and to drink!\\nGreat bites as well!\\nAmbience is pretty happening!\\nClose to offices so very convenient!\\nAnd service is also good\'), (\'Rated 3.0\', "RATED\\n  Its in bellandur,on the road side.Easily reachable Nice rooftop bar. There is no dance floor but they have live music.drinks and food was nice. I would say it\'s a 3.5 over all."), (\'Rated 5.0\', \'RATED\\n  Finally a good place opened up for people living in this side of the city. Its made everyone happy with its food and awesome weekend vibes. I have visited this place on weekend, weekdays, days and anytime a friend is in town and it never has failed me!\'), (\'Rated 4.0\', "RATED\\n  Hands down, the best place to chill. I\'ve been to the outlet at Indirangar, went to this one for the first time. Absolutely loved it. The food is amazing undoubtedly. Ambience is great. We ordered chicken manchow soup, chicken skewers, orange chilli chicken, peanuts, coorgi pork, chicken Peri Peri wings and drinks."), (\'Rated 2.0\', \'RATED\\n  I was honestly not pleased with the ambience or the food. Both were bad. And being a rooftop, there should be some kind of ventilation. It was really hot and there were no fans. The place definitely needs a get up. They need to improve the ambience as soon as possible. The Indiranagar branch is way better than this. I canÃ\x83\\x83Ã\x82\\x83Ã\x83\\x82Ã\x82\\x83Ã\x83\\x83Ã\x82\\x82Ã\x83\\x82Ã\x82Â¢Ã\x83\\x83Ã\x82\\x83Ã\x83\\x82Ã\x82\\x82Ã\x83\\x83Ã\x82\\x82Ã\x83\\x82Ã\x82\\x80Ã\x83\\x83Ã\x82\\x83Ã\x83\\x82Ã\x82\\x82Ã\x83\\x83Ã\x82\\x82Ã\x83\\x82Ã\x82\\x99t complain about the service. The waiters were prompt and ready to help always. Coming to the food, the tikka seemed under cooked because the spices were raw and only the chicken was cooked. The nachos were a mess and the paneer sticks tasted stale. I really think there is room for improvement and since their other branch has such a good name, I think they can live up to the expectations.\'), (\'Rated 3.0\', \'RATED\\n  The initial plan was to go to FishermanÃ\x83\\x83Ã\x82\\x83Ã\x83\\x82Ã\x82\\x83Ã\x83\\x83Ã\x82\\x82Ã\x83\\x82Ã\x82Â¢Ã\x83\\x83Ã\x82\\x83Ã\x83\\x82Ã\x82\\x82Ã\x83\\x83Ã\x82\\x82Ã\x83\\x82Ã\x82\\x80Ã\x83\\x83Ã\x82\\x83Ã\x83\\x82Ã\x82\\x82Ã\x83\\x83Ã\x82\\x82Ã\x83\\x82Ã\x82\\x99s wharf on Haralur Road but then decided to try this place out. Good ambience and a different experience. Food and drinks were ok and had a good time. Would not mind going back.\'), (\'Rated 4.0\', \'RATED\\n  It was always my planning to go there once this time one of my friend called me to visit there.\\nActually I m so happy with this visit it made our evening good place to hangout and fun with friends.\'), (\'Rated 4.0\', \'RATED\\n  I been visiting this place very frequently since 2016. ItÃ\x83\\x83Ã\x82\\x83Ã\x83\\x82Ã\x82\\x83Ã\x83\\x83Ã\x82\\x82Ã\x83\\x82Ã\x82Â¢Ã\x83\\x83Ã\x82\\x83Ã\x83\\x82Ã\x82\\x82Ã\x83\\x83Ã\x82\\x82Ã\x83\\x82Ã\x82\\x80Ã\x83\\x83Ã\x82\\x83Ã\x83\\x82Ã\x82\\x82Ã\x83\\x83Ã\x82\\x82Ã\x83\\x82Ã\x82\\x99s a great place and always has a vibrant crowd. I absolutely love the roof top ambience and I think that the concept of a stock exchange is very cleve. The food and the cocktails are great. I really like the service and itÃ\x83\\x83Ã\x82\\x83Ã\x83\\x82Ã\x82\\x83Ã\x83\\x83Ã\x82\\x82Ã\x83\\x82Ã\x82Â¢Ã\x83\\x83Ã\x82\\x83Ã\x83\\x82Ã\x82\\x82Ã\x83\\x83Ã\x82\\x82Ã\x83\\x82Ã\x82\\x80Ã\x83\\x83Ã\x82\\x83Ã\x83\\x82Ã\x82\\x82Ã\x83\\x83Ã\x82\\x82Ã\x83\\x82Ã\x82\\x99s very nice cause the staff is always very friendly. IÃ\x83\\x83Ã\x82\\x83Ã\x83\\x82Ã\x82\\x83Ã\x83\\x83Ã\x82\\x82Ã\x83\\x82Ã\x82Â¢Ã\x83\\x83Ã\x82\\x83Ã\x83\\x82Ã\x82\\x82Ã\x83\\x83Ã\x82\\x82Ã\x83\\x82Ã\x82\\x80Ã\x83\\x83Ã\x82\\x83Ã\x83\\x82Ã\x82\\x82Ã\x83\\x83Ã\x82\\x82Ã\x83\\x82Ã\x82\\x99d surely recommend Tipsy bull to all of my friends and family.\'), (\'Rated 5.0\', \'RATED\\n  I am very regular to this Place. Several Times I have Visited their Indira Nagar Branch. This outlet is also Very Nice. Amazing Ambiance. Brilliant Hospitality. Mouth watering Food, Quick Friendly Service. Highly Recommamded... Cheers!\\n\\nAmbiance : 5/5\\nFood : 5/5\\nService : 5/5\\nValue for Money : 5/5\'), (\'Rated 4.0\', \'RATED\\n  I have been bere several times, since its close to my place and one of the most happening places in Bellandur.\\nThe ambience is nice and airy since its on the roof top.\\nThe theme is of stock exchange, where prices of alcohol changes with time, and you have to order from the app.\\nYou will get alcohol for cheap before 8pm.\\nFood tastes good and the service is quick.\'), (\'Rated 3.0\', \'RATED\\n  Been here four days back...\\nQuite decent and happening place.\\nWe ordered pitcher of Budweiser and we got the fresh glass with full of lipstick. This was the the first disappointment. The we ordered French fries with cheese and we got potato wedges with cheese.\\nFood presentation was very nice. Taste was good.\\nAmbience was excellent.\'), (\'Rated 4.0\', "RATED\\n  It\'s just awesome . The top up and down really feels like real stock exchange . It\'s really awesome while ordering the drinks based on the rates up n down. Loved the environment and ambiance."), (\'Rated 3.0\', \'RATED\\n  We went for dinner party- food is so so. Drinks are good. Too many mosquitos though. The ambience was good. It is a terrace place. Specially good when it is raining\'), (\'Rated 3.0\', \'RATED\\n  This place is a real good place - worth dining with friends and family !\\nThe theme of this restobar is very pleasing, the ambiance is just too good.\\n\\nThe place is not that much happening for partying and dance floor is also not that big and the DJ is also not of that quality.\\n\\nThis bar exchange has changing prices like sensex. The menu here is quiet exciting and bold.\\n\\nThe taste is YUMMY everything u order is just superb. Additional important thing, the washrooms (separate for male and female) is always clean, there is a dedicated sweeper to keep cleaning it.\'), (\'Rated 4.0\', \'RATED\\n  I have been bere several times, since its close to my place and one of the most happening places in Bellandur.\\nThe ambience is nice and airy since its on the roof top.\\nThe theme is of stock exchange, where prices of alcohol changes with time, and you have to order from the app.\\nYou will get alcohol for cheap before 8pm.\\nFood tastes good and the service is quick.\'), (\'Rated 3.0\', \'RATED\\n  Been here four days back...\\nQuite decent and happening place.\\nWe ordered pitcher of Budweiser and we got the fresh glass with full of lipstick. This was the the first disappointment. The we ordered French fries with cheese and we got potato wedges with cheese.\\nFood presentation was very nice. Taste was good.\\nAmbience was excellent.\'), (\'Rated 4.0\', "RATED\\n  It\'s just awesome . The top up and down really feels like real stock exchange . It\'s really awesome while ordering the drinks based on the rates up n down. Loved the environment and ambiance."), (\'Rated 3.0\', \'RATED\\n  We went for dinner party- food is so so. Drinks are good. Too many mosquitos though. The ambience was good. It is a terrace place. Specially good when it is raining\'), (\'Rated 3.0\', \'RATED\\n  This place is a real good place - worth dining with friends and family !\\nThe theme of this restobar is very pleasing, the ambiance is just too good.\\n\\nThe place is not that much happening for partying and dance floor is also not that big and the DJ is also not of that quality.\\n\\nThis bar exchange has changing prices like sensex. The menu here is quiet exciting and bold.\\n\\nThe taste is YUMMY everything u order is just superb. Additional important thing, the washrooms (separate for male and female) is always clean, there is a dedicated sweeper to keep cleaning it.\'), (\'Rated 4.0\', \'RATED\\n  I have been bere several times, since its close to my place and one of the most happening places in Bellandur.\\nThe ambience is nice and airy since its on the roof top.\\nThe theme is of stock exchange, where prices of alcohol changes with time, and you have to order from the app.\\nYou will get alcohol for cheap before 8pm.\\nFood tastes good and the service is quick.\'), (\'Rated 3.0\', \'RATED\\n  Been here four days back...\\nQuite decent and happening place.\\nWe ordered pitcher of Budweiser and we got the fresh glass with full of lipstick. This was the the first disappointment. The we ordered French fries with cheese and we got potato wedges with cheese.\\nFood presentation was very nice. Taste was good.\\nAmbience was excellent.\'), (\'Rated 4.0\', "RATED\\n  It\'s just awesome . The top up and down really feels like real stock exchange . It\'s really awesome while ordering the drinks based on the rates up n down. Loved the environment and ambiance."), (\'Rated 3.0\', \'RATED\\n  We went for dinner party- food is so so. Drinks are good. Too many mosquitos though. The ambience was good. It is a terrace place. Specially good when it is raining\'), (\'Rated 3.0\', \'RATED\\n  This place is a real good place - worth dining with friends and family !\\nThe theme of this restobar is very pleasing, the ambiance is just too good.\\n\\nThe place is not that much happening for partying and dance floor is also not that big and the DJ is also not of that quality.\\n\\nThis bar exchange has changing prices like sensex. The menu here is quiet exciting and bold.\\n\\nThe taste is YUMMY everything u order is just superb. Additional important thing, the washrooms (separate for male and female) is always clean, there is a dedicated sweeper to keep cleaning it.\'), (\'Rated 4.0\', \'RATED\\n  I have been bere several times, since its close to my place and one of the most happening places in Bellandur.\\nThe ambience is nice and airy since its on the roof top.\\nThe theme is of stock exchange, where prices of alcohol changes with time, and you have to order from the app.\\nYou will get alcohol for cheap before 8pm.\\nFood tastes good and the service is quick.\'), (\'Rated 3.0\', \'RATED\\n  Been here four days back...\\nQuite decent and happening place.\\nWe ordered pitcher of Budweiser and we got the fresh glass with full of lipstick. This was the the first disappointment. The we ordered French fries with cheese and we got potato wedges with cheese.\\nFood presentation was very nice. Taste was good.\\nAmbience was excellent.\'), (\'Rated 4.0\', "RATED\\n  It\'s just awesome . The top up and down really feels like real stock exchange . It\'s really awesome while ordering the drinks based on the rates up n down. Loved the environment and ambiance."), (\'Rated 3.0\', \'RATED\\n  We went for dinner party- food is so so. Drinks are good. Too many mosquitos though. The ambience was good. It is a terrace place. Specially good when it is raining\'), (\'Rated 3.0\', \'RATED\\n  This place is a real good place - worth dining with friends and family !\\nThe theme of this restobar is very pleasing, the ambiance is just too good.\\n\\nThe place is not that much happening for partying and dance floor is also not that big and the DJ is also not of that quality.\\n\\nThis bar exchange has changing prices like sensex. The menu here is quiet exciting and bold.\\n\\nThe taste is YUMMY everything u order is just superb. Additional important thing, the washrooms (separate for male and female) is always clean, there is a dedicated sweeper to keep cleaning it.\'), (\'Rated 4.0\', \'RATED\\n  I have been bere several times, since its close to my place and one of the most happening places in Bellandur.\\nThe ambience is nice and airy since its on the roof top.\\nThe theme is of stock exchange, where prices of alcohol changes with time, and you have to order from the app.\\nYou will get alcohol for cheap before 8pm.\\nFood tastes good and the service is quick.\'), (\'Rated 3.0\', \'RATED\\n  Been here four days back...\\nQuite decent and happening place.\\nWe ordered pitcher of Budweiser and we got the fresh glass with full of lipstick. This was the the first disappointment. The we ordered French fries with cheese and we got potato wedges with cheese.\\nFood presentation was very nice. Taste was good.\\nAmbience was excellent.\'), (\'Rated 4.0\', "RATED\\n  It\'s just awesome . The top up and down really feels like real stock exchange . It\'s really awesome while ordering the drinks based on the rates up n down. Loved the environment and ambiance."), (\'Rated 3.0\', \'RATED\\n  We went for dinner party- food is so so. Drinks are good. Too many mosquitos though. The ambience was good. It is a terrace place. Specially good when it is raining\'), (\'Rated 3.0\', \'RATED\\n  This place is a real good place - worth dining with friends and family !\\nThe theme of this restobar is very pleasing, the ambiance is just too good.\\n\\nThe place is not that much happening for partying and dance floor is also not that big and the DJ is also not of that quality.\\n\\nThis bar exchange has changing prices like sensex. The menu here is quiet exciting and bold.\\n\\nThe taste is YUMMY everything u order is just superb. Additional important thing, the washrooms (separate for male and female) is always clean, there is a dedicated sweeper to keep cleaning it.\'), (\'Rated 4.0\', \'RATED\\n  I have been bere several times, since its close to my place and one of the most happening places in Bellandur.\\nThe ambience is nice and airy since its on the roof top.\\nThe theme is of stock exchange, where prices of alcohol changes with time, and you have to order from the app.\\nYou will get alcohol for cheap before 8pm.\\nFood tastes good and the service is quick.\'), (\'Rated 3.0\', \'RATED\\n  Been here four days back...\\nQuite decent and happening place.\\nWe ordered pitcher of Budweiser and we got the fresh glass with full of lipstick. This was the the first disappointment. The we ordered French fries with cheese and we got potato wedges with cheese.\\nFood presentation was very nice. Taste was good.\\nAmbience was excellent.\'), (\'Rated 4.0\', "RATED\\n  It\'s just awesome . The top up and down really feels like real stock exchange . It\'s really awesome while ordering the drinks based on the rates up n down. Loved the environment and ambiance."), (\'Rated 3.0\', \'RATED\\n  We went for dinner party- food is so so. Drinks are good. Too many mosquitos though. The ambience was good. It is a terrace place. Specially good when it is raining\'), (\'Rated 3.0\', \'RATED\\n  This place is a real good place - worth dining with friends and family !\\nThe theme of this restobar is very pleasing, the ambiance is just too good.\\n\\nThe place is not that much happening for partying and dance floor is also not that big and the DJ is also not of that quality.\\n\\nThis bar exchange has changing prices like sensex. The menu here is quiet exciting and bold.\\n\\nThe taste is YUMMY everything u order is just superb. Additional important thing, the washrooms (separate for male and female) is always clean, there is a dedicated sweeper to keep cleaning it.\'), (\'Rated 4.0\', \'RATED\\n  I have been bere several times, since its close to my place and one of the most happening places in Bellandur.\\nThe ambience is nice and airy since its on the roof top.\\nThe theme is of stock exchange, where prices of alcohol changes with time, and you have to order from the app.\\nYou will get alcohol for cheap before 8pm.\\nFood tastes good and the service is quick.\'), (\'Rated 3.0\', \'RATED\\n  Been here four days back...\\nQuite decent and happening place.\\nWe ordered pitcher of Budweiser and we got the fresh glass with full of lipstick. This was the the first disappointment. The we ordered French fries with cheese and we got potato wedges with cheese.\\nFood presentation was very nice. Taste was good.\\nAmbience was excellent.\'), (\'Rated 4.0\', "RATED\\n  It\'s just awesome . The top up and down really feels like real stock exchange . It\'s really awesome while ordering the drinks based on the rates up n down. Loved the environment and ambiance."), (\'Rated 3.0\', \'RATED\\n  We went for dinner party- food is so so. Drinks are good. Too many mosquitos though. The ambience was good. It is a terrace place. Specially good when it is raining\'), (\'Rated 3.0\', \'RATED\\n  This place is a real good place - worth dining with friends and family !\\nThe theme of this restobar is very pleasing, the ambi

KeyboardInterrupt:

In [12]:
producer.flush()

In [ ]:
import requests

url = "https://pizza-and-desserts.p.rapidapi.com/pizzas"

headers = {
	"x-rapidapi-key": "07bed90cc0msh0176ef69f59c718p1a0186jsnf286fbda9188",
	"x-rapidapi-host": "pizza-and-desserts.p.rapidapi.com",
	"Content-Type": "application/json"
}

response = requests.get(url, headers=headers)

data = response.json()
print(data)

In [ ]:
while True:
    producer.send('project1' , value = data)

In [ ]:
while True:
    stock = df.sample(1).to_dict(orient = "records")[0]
    producer.send('project1' , value = stock)